# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

r_packages:
  - covr

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required

      r_binary_packages:
        - knitr
        - htmltools
        - rlang
        - testthat
        - roxygen2
        - rmarkdown
        - pkgdown
        - covr
        - spelling
        - dplyr
        - DT
        - ggplot2

after_success:
  - Rscript -e 'library(covr); codecov()'

repos:
  CRAN: https://cloud.r-project.org
